update org readme
github-community/.github pull request #11
Opened 2022-07-15 13:55 UTC by tuves

main page readme updates

2022-07-15 20:59 UTC, jenna-wolf commented on profile/README.md
> +  <img width="612" height="135" src="https://user-images.githubusercontent.com/49915749/179235266-19730a30-47bf-47b1-9456-e03f64cfc0dd.png">
@tuves we will not be able to include this lockup here as it is to only be used for promotional purposes. So we can just keep the headline without the logo.

2022-07-15 21:01 UTC, jenna-wolf requested changes
@tuves  I would just remove the lockup and then remember to include the category post link. Then we should be set! Thanks so much :heart:

2022-07-25 18:51 UTC, ettaboyle approved these changes
Approved 🚀

2022-07-25 18:52 UTC, merged

2022-08-01 02:37 UTC, IsaqueDato commented
Gente eu tô bem perdido, nunca soube pra onde foi programação, mas é minha chance não posso perder.